spring.application.name=application
#debug=true

spring.datasource.url=jdbc:mysql://localhost:3306/javaSpringDb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.sq

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yourmailId
spring.mail.password=your password

sender.mail.id=sendermailid

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
